<a href="https://colab.research.google.com/github/maryb2002/Exercises-about-Numpy-library/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a= np.random.randint(1, 11, (3, 4))
b= np.random.randint(1, 11, (3, 4))
print(a)
print(a.shape)
print(b)
print(b.shape)
print('adding numbers')
print(a+b)
print('subtracting numbers')
print(a-b)
print('multiplier numbers')
print(a*b)


print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 9  2  3 10]
 [ 4  3  8  6]
 [ 6  6  1  6]]
(3, 4)
[[3 2 5 3]
 [4 9 6 4]
 [5 3 2 5]]
(3, 4)
adding numbers
[[12  4  8 13]
 [ 8 12 14 10]
 [11  9  3 11]]
subtracting numbers
[[ 6  0 -2  7]
 [ 0 -6  2  2]
 [ 1  3 -1  1]]
multiplier numbers
[[27  4 15 30]
 [16 27 48 24]
 [30 18  2 30]]
[[12  4  8 13]
 [ 8 12 14 10]
 [11  9  3 11]]
[[27  4 15 30]
 [16 27 48 24]
 [30 18  2 30]]
[[3.         1.         0.6        3.33333333]
 [1.         0.33333333 1.33333333 1.5       ]
 [1.2        2.         0.5        1.2       ]]


In [ ]:
a = np.random.randint(1, 11, size=(2, 3))
b = np.random.randint(1, 11, size=(3, 4 ))

print(a)
print(a.shape)
print(b)
print(b.shape)
print(np.dot(a,b))

[[ 4  5  7]
 [ 6 10  5]]
(2, 3)
[[10  1  6  4]
 [ 4  2  4  4]
 [10  3  4  1]]
(3, 4)
[[130  35  72  43]
 [150  41  96  69]]


In [ ]:
a= np.random.randint(1, 11, (2, 2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[3 3]
 [9 2]]
[[3 9]
 [3 2]]


In [ ]:
a= np.random.randint(1, 11, (4, 3))
b= np.array((1,0,2))
print(a)
print(a.shape)
print(b)
print(b.shape)

c=np.empty_like(a)

print(c.shape)
print('----------------')
print(c)

[[10  4  6]
 [ 7  6  6]
 [ 9 10  8]
 [ 9  7  6]]
(4, 3)
[1 0 2]
(3,)
(4, 3)
----------------
[[ 9  2  3]
 [10  4  3]
 [ 8  6  6]
 [ 6  1  6]]


In [ ]:
for i in range(4):
  c[i,:]=a[i,:]+b

print(a)
print(b)
print(c)

c=a+b
print(c)

[[10  4  6]
 [ 7  6  6]
 [ 9 10  8]
 [ 9  7  6]]
[1 0 2]
[[11  4  8]
 [ 8  6  8]
 [10 10 10]
 [10  7  8]]
[[11  4  8]
 [ 8  6  8]
 [10 10 10]
 [10  7  8]]


In [ ]:
a=np.array((1,2,3))

print(a)
tmp=np.tile(a,(6,1))
print(tmp)


[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a= np.random.randint(0,10 , (6, 6))
print(a)
aux=np.mean(a)
print(aux)

print(a.mean(axis=1))
print(a.mean(axis=0))

[[7 7 5 9 6 6]
 [1 8 0 7 6 6]
 [8 3 0 8 5 5]
 [8 0 8 0 7 2]
 [9 5 6 7 9 9]
 [7 3 4 5 5 1]]
5.333333333333333
[6.66666667 4.66666667 4.83333333 4.16666667 7.5        4.16666667]
[6.66666667 4.33333333 3.83333333 6.         6.33333333 4.83333333]
