<a href="https://colab.research.google.com/github/maryb2002/Exercises-about-Numpy-library/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

aux=np.array({1,2,4,5})
print(aux)
print(aux.shape)

aux=np.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))

tmp=np.zeros((4,4))
print(tmp)
tmp=np.full((4,4),5)
print(tmp)
tmp=np.eye(4,4)
print(tmp)
print('--------------')
tmp=np.ones((4,4))
print(tmp)

{1, 2, 4, 5}
()
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
tmp=10*np.random.random((3,3))
print(tmp)

[[5.1160227  3.10762712 3.43469931]
 [7.7797869  1.12312808 0.16009195]
 [3.48736675 4.98286513 5.1919664 ]]


In [ ]:
print(tmp[:2,:2])

[[5.1160227  3.10762712]
 [7.7797869  1.12312808]]


In [ ]:
print(tmp[:2,1:3])

[[3.10762712 3.43469931]
 [1.12312808 0.16009195]]


In [ ]:
print(tmp[:1,1])
print(tmp[2,2])
print(tmp[2,1:3])

[3.10762712]
5.19196639743515
[4.98286513 5.1919664 ]


In [ ]:
tmp=10*np.random.random((3,3))
print(tmp)

[[2.43211228 5.53169256 2.06884706]
 [0.66166169 2.75660834 5.59086588]
 [0.44957524 0.57364098 6.08184287]]


In [ ]:
mask=(tmp>=2)&(tmp<=4)

In [ ]:
tmp= np.random.randint(1, 101, (4, 4))
print(tmp)
mask =np.mod(tmp, 2) == 0
matriz_pares = tmp[mask]
print(tmp[mask])

[[ 41  34  18  16]
 [ 86  68  82  82]
 [ 58  19  62  46]
 [ 28  65 100  80]]
[ 34  18  16  86  68  82  82  58  62  46  28 100  80]
